### ISSUE TITLE
Stopped working after updating to 7.2.x

### ISSUE THREAD

**Issue by Zloi78** [kichetof/AutoBlockIPList#1]
The script produces the following errors after updating to 7.2.x (reinstallation of requirements.txt was done after the update)

_Traceback (most recent call last):
  File "/volume1/Backup/IMAGES/DS/Blocklist/AutoBlockIPList.py", line 136, in <module>
    args = parse_args()
  File "/volume1/Backup/IMAGES/DS/Blocklist/AutoBlockIPList.py", line 122, in parse_args
    a = parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2407, in _get_values
    value = [self._get_value(action, v) for v in arg_strings]
  File "/usr/lib/python3.8/argparse.py", line 2407, in <listcomp>
    value = [self._get_value(action, v) for v in arg_strings]
  File "/usr/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/volume1/Backup/IMAGES/DS/Blocklist/AutoBlockIPList.py", line 76, in url
    if isinstance(validator, validators.ValidationFailure):
AttributeError: module 'validators' has no attribute 'ValidationFailure'_

**Comment by kichetof** [comment]
@Zloi78 thanks for your feedback.
I was able to reproduce error. Normally everything should be fine with new release: https://github.com/kichetof/AutoBlockIPList/releases/tag/1.0.1

Let me know!

**Comment by Zloi78** [comment]
> @Zloi78 thanks for your feedback. I was able to reproduce error. Normally everything should be fine with new release: https://github.com/kichetof/AutoBlockIPList/releases/tag/1.0.1
> 
> Let me know!

Yes. Now everything works without errors. Thank you!

**Comment by kichetof** [comment]
Fixed with new release! Thanks for reporting it! 🎉
